// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: currencies.sql

package sqlc

import (
	"context"
)

const listActiveCurrencies = `-- name: ListActiveCurrencies :many
SELECT code,
    name,
    exponent,
    is_active
FROM currencies
WHERE is_active = true
`

type ListActiveCurrenciesRow struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	Exponent int16  `json:"exponent"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) ListActiveCurrencies(ctx context.Context) ([]ListActiveCurrenciesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCurrenciesRow{}
	for rows.Next() {
		var i ListActiveCurrenciesRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Exponent,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
