// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EntryType string

const (
	EntryTypeDEBIT  EntryType = "DEBIT"
	EntryTypeCREDIT EntryType = "CREDIT"
)

func (e *EntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryType(s)
	case string:
		*e = EntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryType: %T", src)
	}
	return nil
}

type NullEntryType struct {
	EntryType EntryType `json:"entry_type"`
	Valid     bool      `json:"valid"` // Valid is true if EntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryType), nil
}

type Account struct {
	ID        uuid.UUID `json:"id"`
	OwnerID   string    `json:"owner_id"`
	Type      string    `json:"type"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type BalanceSnapshot struct {
	ID                uuid.UUID `json:"id"`
	AccountID         uuid.UUID `json:"account_id"`
	Balance           int64     `json:"balance"`
	LastEntrySequence int64     `json:"last_entry_sequence"`
	CreatedAt         time.Time `json:"created_at"`
}

type Currency struct {
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Exponent  int16     `json:"exponent"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	Type          EntryType `json:"type"`
	Amount        int64     `json:"amount"`
	EntrySequence int64     `json:"entry_sequence"`
	CreatedAt     time.Time `json:"created_at"`
}

type IdempotencyRecord struct {
	Key          string      `json:"key"`
	RequestHash  string      `json:"request_hash"`
	Status       string      `json:"status"`
	StatusCode   pgtype.Int4 `json:"status_code"`
	ResponseBody []byte      `json:"response_body"`
	CreatedAt    time.Time   `json:"created_at"`
	ExpiresAt    time.Time   `json:"expires_at"`
}

type Transaction struct {
	ID                  uuid.UUID     `json:"id"`
	Reference           string        `json:"reference"`
	Type                string        `json:"type"`
	Currency            string        `json:"currency"`
	ParentTransactionID uuid.NullUUID `json:"parent_transaction_id"`
	Description         string        `json:"description"`
	Metadata            []byte        `json:"metadata"`
	TransactionDate     time.Time     `json:"transaction_date"`
	CreatedAt           time.Time     `json:"created_at"`
}
