// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntries(ctx context.Context, arg []CreateEntriesParams) (int64, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetAccountBalance(ctx context.Context) (int32, error)
	ListActiveCurrencies(ctx context.Context) ([]ListActiveCurrenciesRow, error)
}

var _ Querier = (*Queries)(nil)
