// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type CreateEntriesParams struct {
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	Type          EntryType `json:"type"`
	Amount        int64     `json:"amount"`
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
        reference,
        type,
        currency,
        parent_transaction_id,
        description,
        metadata,
        transaction_date
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, reference, type, currency, parent_transaction_id, description, metadata, transaction_date, created_at
`

type CreateTransactionParams struct {
	Reference           string        `json:"reference"`
	Type                string        `json:"type"`
	Currency            string        `json:"currency"`
	ParentTransactionID uuid.NullUUID `json:"parent_transaction_id"`
	Description         string        `json:"description"`
	Metadata            []byte        `json:"metadata"`
	TransactionDate     time.Time     `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Reference,
		arg.Type,
		arg.Currency,
		arg.ParentTransactionID,
		arg.Description,
		arg.Metadata,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.Currency,
		&i.ParentTransactionID,
		&i.Description,
		&i.Metadata,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}
