// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type EntryType string

const (
	EntryTypeDEBIT  EntryType = "DEBIT"
	EntryTypeCREDIT EntryType = "CREDIT"
)

func (e *EntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryType(s)
	case string:
		*e = EntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryType: %T", src)
	}
	return nil
}

type NullEntryType struct {
	EntryType EntryType `json:"entry_type"`
	Valid     bool      `json:"valid"` // Valid is true if EntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryType), nil
}

type Account struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   string             `json:"owner_id"`
	Type      string             `json:"type"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BalanceSnapshot struct {
	ID                pgtype.UUID        `json:"id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	Balance           int64              `json:"balance"`
	LastEntrySequence int64              `json:"last_entry_sequence"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Entry struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	Type          EntryType          `json:"type"`
	Amount        int64              `json:"amount"`
	EntrySequence int64              `json:"entry_sequence"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyRecord struct {
	Key          string             `json:"key"`
	RequestHash  string             `json:"request_hash"`
	Status       string             `json:"status"`
	StatusCode   pgtype.Int4        `json:"status_code"`
	ResponseBody []byte             `json:"response_body"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Transaction struct {
	ID          pgtype.UUID        `json:"id"`
	Reference   string             `json:"reference"`
	Type        string             `json:"type"`
	Status      string             `json:"status"`
	Description string             `json:"description"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
